server:
  port: 8080
spring:
  application:
    name: sampleapp  
eureka:
    instance:
      preferIpAddress: false
    client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://host.docker.internal:9091/eureka
ribbon:
  eureka:
    enabled: false
mongorepo:
  ribbon:
    eureka:
      enabled:  false
    listOfServers: ${${mongok8sservice}_SERVICE_HOST}:${${mongok8sservice}_SERVICE_PORT}
    ServerListRefreshInterval: 15000
mongosample:  mongorepo
mongok8sservice:  MONGOSAMPLE_HTTP
emp:
  create:
    url: http://${mongosample}/create
MONGOSAMLE: MONGOSAMPLE_HTTP