server:
  port: 8080
spring:
  application:
    name: samplemvc
  cloud:
    kubernetes:
      enabled:  true
      discovery:
        enabled:  true  
appservice:
  discovery:
    host: host.docker.internal
    port: 9091      
eureka:
    instance:
      preferIpAddress: false
      hostname: ${appservice.discovery.host}
    client:
      registerWithEureka: false
      fetchRegistry: false
      enabled:  false
      serviceUrl:
        defaultZone: http://${appservice.discovery.host}:${appservice.discovery.port}/eureka  
ribbon:
  eureka:
    enabled: false
emp:
  create:
    url: http://mongorepo/create 