server:
  port: 8080
spring:
  application:
    name: sampleapp  
eureka:
    instance:
      preferIpAddress: true
      hostname: host.docker.internal
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://host.docker.internal:9091/eureka    
ribbon:
  eureka:
    enabled: true
emp:
  create:
    url: http://mongorepo/create